### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [dectrfov/Y-net#3]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by huckiyang** [comment]
@PINTO0309 thank you for your efforts of model_zoo to the community.
Our license is Apache License 2.0. Many thanks!

https://github.com/dectrfov/Y-net/pull/4

**Comment by PINTO0309** [comment]
Thank you!
